import { Bell, FileText, PackageCheck, Quote, Route, Users } from 'lucide-react'
import { useState } from 'react'
import { useI18n } from '@/i18n/i18n'
import Reveal from '@/components/Reveal'
import { getPlatformRequests, type PlatformRequest } from '@/lib/request-store'

const ITEMS = [
  { icon: Quote, label: 'portal.requests', value: '03' }, { icon: PackageCheck, label: 'portal.orders', value: '01' }, { icon: Route, label: 'portal.shipments', value: '02' }, { icon: FileText, label: 'portal.documents', value: '08' },
] as const

export default function Portal() {
  const { t } = useI18n()
  const [requests] = useState<PlatformRequest[]>(getPlatformRequests)
  const activity = [...requests.map((request) => ({ reference: request.reference, label: t('portal.requestSubmitted') })), { reference: 'NSS-7K4M-2026', label: t('tracking.inTransit') }, { reference: 'RFQ-2026-014', label: t('portal.quoteReady') }]
  return <main className="min-h-screen bg-[var(--bg)] pt-32"><section className="mx-auto max-w-7xl px-6 pb-20 md:px-12"><Reveal className="flex flex-col gap-5 border-b border-[rgba(var(--gold-rgb),0.16)] pb-10 md:flex-row md:items-end md:justify-between"><div><p className="nss-section-tag">{t('portal.tag')}</p><h1 className="nss-h2 mt-4 text-3xl md:text-5xl">{t('portal.heading')}</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-[rgba(var(--text-rgb),0.58)]">{t('portal.sub')}</p></div><button className="nss-btn-primary inline-flex w-fit items-center gap-2 rounded-sm px-5 py-3 text-sm font-bold"><Bell size={15} />{t('portal.notifications')}</button></Reveal><div className="mt-10 grid gap-px overflow-hidden border border-[rgba(var(--gold-rgb),0.16)] bg-[rgba(var(--gold-rgb),0.16)] sm:grid-cols-2 lg:grid-cols-4">{ITEMS.map((item, index) => <Reveal key={item.label} delay={index * 70}><div className="flex min-h-44 flex-col bg-[var(--panel)] p-6"><item.icon size={20} className="text-[rgb(var(--gold-rgb))]" /><p className="nss-display mt-auto text-4xl">{item.label === 'portal.requests' ? String(requests.length).padStart(2, '0') : item.value}</p><p className="nss-mono mt-2 text-[11px] tracking-[0.15em] text-[rgba(var(--text-rgb),0.56)] uppercase">{t(item.label)}</p></div></Reveal>)}</div><div className="mt-10 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Reveal><section className="nss-card overflow-hidden"><div className="flex items-center justify-between border-b border-[rgba(var(--gold-rgb),0.13)] p-6"><div><p className="nss-section-tag">{t('portal.activity')}</p><h2 className="nss-display mt-2 text-xl">{t('portal.recent')}</h2></div><Route size={20} className="text-[rgb(var(--gold-rgb))]" /></div><div className="divide-y divide-[rgba(var(--gold-rgb),0.11)]">{activity.slice(0, 3).map((item) => <div key={item.reference} className="flex items-center justify-between gap-4 p-6"><div><p className="nss-mono text-[11px] tracking-[0.12em] text-[rgb(var(--gold-rgb))]">{item.reference}</p><p className="mt-2 text-sm text-[rgba(var(--text-rgb),0.7)]">{item.label}</p></div><span className="h-2 w-2 rounded-full bg-[rgb(var(--gold-rgb))]" /></div>)}</div></section></Reveal><Reveal delay={80}><section className="nss-card p-6"><Users size={21} className="text-[rgb(var(--gold-rgb))]" /><h2 className="nss-display mt-5 text-xl">{t('portal.team')}</h2><p className="mt-3 text-sm leading-relaxed text-[rgba(var(--text-rgb),0.57)]">{t('portal.teamSub')}</p><button className="mt-6 border border-[rgba(var(--gold-rgb),0.34)] px-4 py-2.5 text-xs font-semibold text-[rgb(var(--gold-rgb))]">{t('portal.manage')}</button></section></Reveal></div></section></main>
}
